name: kyc test

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: kyc-app
  cancel-in-progress: false
  
env:
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  build:
    name: Build kyc app
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Project
      run: |
        VITE_AWS_REGION=${{ env.AWS_REGION }} \
        VITE_API_BASEURL=${{vars.VITE_API_BASEURL}} \
        VITE_AWS_COGNITO_IDENTITY_POOL_ID=${{ vars.VITE_AWS_COGNITO_IDENTITY_POOL_ID }} \
        VITE_AWS_USER_POOLS_ID=${{ vars.VITE_AWS_USER_POOLS_ID }} \
        VITE_AWS_USER_POOLS_WEB_CLIENT_ID=${{ vars.VITE_AWS_USER_POOLS_WEB_CLIENT_ID }} \
        npm run build

    - name: Upload Build Files
      uses: actions/upload-artifact@master
      with:
        name: kyc-build-files-dev
        path: |
          ./dist
          ./copilot

    - name: Send notification
      if: failure()
      uses: jchrist/google-chat-github-action@v1
      with:
        name: Build KYC app in Dev
        url: ${{ secrets.GMAIL_WORKSPACE }}
        status: ${{ job.status }}
        collapse: 1
      continue-on-error: true

  deploy:
    needs: build
    name: Deploy KYC App
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Get build artifact
      uses: actions/download-artifact@master
      with:
        name: kyc-build-files-dev

    - name: Set Certificate ARN
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'copilot/kyc-app/manifest.yml'
        propertyPath: 'environments.dev.http.certificate'
        value: ${{ secrets.CERTIFICATE_ARN }}
        commitChange: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install aws copilot CLI
      uses: ksivamuthu/aws-copilot-github-action@v0.0.8
      with:
        command: install

    - name: Set up Copilot and Deploy App
      run: |
        copilot app init aml
        copilot app upgrade
        copilot svc deploy --name kyc-test --env dev
      
    # - name: Send notification
    #   if: success() || failure()
    #   uses: jchrist/google-chat-github-action@v1
    #   with:
    #     name: Deploy KYC App in Dev
    #     url: ${{ secrets.GMAIL_WORKSPACE }}
    #     status: ${{ job.status }}
    #     collapse: 1
    #   continue-on-error: true
